CREATE TABLE IF NOT EXISTS inventory (
    product_id VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    stock INT NOT NULL CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(50) PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
    id SERIAL PRIMARY KEY,
    order_id VARCHAR(50) REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id VARCHAR(50) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(255) NOT NULL,
    buyer_ref VARCHAR(255) NOT NULL UNIQUE,
    request_id VARCHAR(255) NOT NULL UNIQUE,
    po_number VARCHAR(255),
    cases INTEGER NOT NULL,
    units INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS channel_state (
    id INTEGER PRIMARY KEY,
    cursor BIGINT NOT NULL DEFAULT 0,
    instance_id VARCHAR(80),
    started_at VARCHAR(80),
    online BOOLEAN NOT NULL DEFAULT FALSE,
    listing_count INTEGER NOT NULL DEFAULT 0,
    decision_count INTEGER NOT NULL DEFAULT 0,
    backorder_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT
);

CREATE TABLE IF NOT EXISTS marketplace_orders (
    id BIGSERIAL PRIMARY KEY,
    tiangge_order_id VARCHAR(100) NOT NULL UNIQUE,
    placed_event_id VARCHAR(150) NOT NULL UNIQUE,
    shop_order_id VARCHAR(100) NOT NULL,
    lines_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS marketplace_events (
    id BIGSERIAL PRIMARY KEY,
    event_id VARCHAR(150) NOT NULL UNIQUE,
    sequence BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL
);

INSERT INTO inventory (product_id, product_name, stock) VALUES
    ('P100', 'Mechanical Keyboard', 25),
    ('P200', 'Wireless Mouse', 10),
    ('P300', 'USB-C Monitor Hub', 5)
ON CONFLICT (product_id) DO NOTHING;